<div class="space-y-6">
    <x-page-header eyebrow="Administration" title="Paramètres" description="Configurez l’identité, les règles de facturation, les documents et les accès."></x-page-header>

    <div class="grid min-w-0 gap-5 lg:grid-cols-[230px_minmax(0,1fr)]">
        <nav class="panel h-fit min-w-0 overflow-hidden p-2 lg:sticky lg:top-[100px]">
            <div class="table-scroll flex max-w-full gap-1 overflow-x-auto lg:flex-col">
                @foreach([
                    ['company','Entreprise','building'],['billing','Facturation','receipt'],['documents','Documents PDF','file'],['users','Utilisateurs','users']
                ] as [$key,$label,$icon])<button wire:click="selectSection('{{ $key }}')" class="flex shrink-0 items-center gap-3 rounded-xl px-3 py-2.5 text-left text-xs font-bold transition lg:w-full {{ $section === $key ? 'bg-indigo-50 text-indigo-700' : 'text-slate-500 hover:bg-slate-50 hover:text-slate-800' }}"><x-icon :name="$icon" :size="17"/><span class="flex-1">{{ $label }}</span>@if($section === $key)<span class="hidden size-1.5 rounded-full bg-indigo-500 lg:block"></span>@endif</button>@endforeach
            </div>
        </nav>

        <div class="min-w-0">
            @if($section !== 'users')
                <form wire:submit="save" class="space-y-5">
                    @if($section === 'company')
                        <section class="panel overflow-hidden"><div class="border-b border-slate-100 px-5 py-4 sm:px-6"><h3 class="font-extrabold text-slate-950">Identité de l’entreprise</h3><p class="mt-0.5 text-xs text-slate-400">Informations visibles sur vos documents commerciaux</p></div><div class="grid gap-6 p-5 sm:p-6 xl:grid-cols-[180px_1fr]">
                            <div><span class="label">Logo</span><label class="flex aspect-square w-full max-w-[180px] cursor-pointer flex-col items-center justify-center overflow-hidden rounded-2xl border border-dashed border-slate-300 bg-slate-50 text-center transition hover:border-indigo-300 hover:bg-indigo-50">@if($logo)<img src="{{ $logo->temporaryUrl() }}" class="h-full w-full object-contain p-3" alt="Aperçu">@elseif($logoPath)<img src="{{ asset('storage/'.$logoPath) }}" class="h-full w-full object-contain p-3" alt="Logo">@else<span class="grid size-11 place-items-center rounded-xl bg-white text-indigo-600 shadow-sm"><x-icon name="building" :size="21"/></span><span class="mt-3 text-xs font-bold text-slate-600">Ajouter un logo</span><span class="mt-1 text-[10px] text-slate-400">PNG ou JPG · 2 Mo max.</span>@endif<input wire:model="logo" type="file" accept="image/*" class="sr-only"></label>@error('logo')<small class="mt-1 block text-xs text-rose-600">{{ $message }}</small>@enderror</div>
                            <div class="grid gap-5 sm:grid-cols-2"><label class="sm:col-span-2"><span class="label">Nom de l’entreprise *</span><input wire:model="form.company_name" class="field">@error('form.company_name')<small class="mt-1 block text-xs text-rose-600">{{ $message }}</small>@enderror</label><label class="sm:col-span-2"><span class="label">Activité / description</span><input wire:model="form.company_description" class="field" placeholder="Ex. Transport, logistique et livraison"></label><label><span class="label">Adresse email</span><input wire:model="form.company_email" type="email" class="field" placeholder="contact@entreprise.com"></label><label><span class="label">Téléphone</span><input wire:model="form.company_phone" class="field"></label><label class="sm:col-span-2"><span class="label">Adresse complète</span><textarea wire:model="form.company_address" rows="2" class="field"></textarea></label><label><span class="label">NIF</span><input wire:model="form.company_tax_number" class="field"></label></div>
                        </div></section>
                    @elseif($section === 'billing')
                        <section class="panel overflow-hidden"><div class="border-b border-slate-100 px-5 py-4 sm:px-6"><h3 class="font-extrabold text-slate-950">Règles de facturation</h3><p class="mt-0.5 text-xs text-slate-400">Valeurs proposées lors de la création des futurs documents</p></div><div class="grid gap-5 p-5 sm:grid-cols-2 sm:p-6 xl:grid-cols-3"><label><span class="label">Devise par défaut</span><input wire:model="form.currency" class="field" placeholder="XOF, EUR, USD…"></label><label><span class="label">TVA activée</span><select wire:model.live="form.tax_enabled" class="field"><option value="1">Oui, appliquer la TVA</option><option value="0">Non, désactiver la TVA</option></select></label><label><span class="label">Taux de TVA par défaut</span><div class="relative"><input wire:model="form.tax_rate" type="number" min="0" max="100" step="0.01" class="field pr-8" @disabled($form['tax_enabled'] === '0')><span class="absolute right-3 top-1/2 -translate-y-1/2 text-xs font-bold text-slate-400">%</span></div></label><label><span class="label">Préfixe des factures</span><input wire:model="form.invoice_prefix" class="field"></label><label><span class="label">Préfixe des proformas</span><input wire:model="form.proforma_prefix" class="field"></label><label><span class="label">Préfixe des devis</span><input wire:model="form.quotation_prefix" class="field"></label><label><span class="label">Chiffres du compteur</span><input wire:model="form.number_digits" type="number" min="3" max="10" class="field"></label><label><span class="label">Échéance par défaut</span><div class="relative"><input wire:model="form.payment_terms_days" type="number" min="0" max="365" class="field pr-16"><span class="absolute right-3 top-1/2 -translate-y-1/2 text-xs font-bold text-slate-400">jours</span></div></label></div><div class="mx-5 mb-5 rounded-xl border border-indigo-100 bg-indigo-50 p-4 text-xs leading-5 text-indigo-700 sm:mx-6 sm:mb-6"><strong>Exemple de numérotation :</strong> {{ $form['invoice_prefix'] ?: 'FAC' }}-{{ now()->format('Y') }}-{{ str_pad('1',(int)($form['number_digits'] ?: 5),'0',STR_PAD_LEFT) }}</div></section>
                    @elseif($section === 'documents')
                        <section class="panel overflow-hidden"><div class="border-b border-slate-100 px-5 py-4 sm:px-6"><h3 class="font-extrabold text-slate-950">Contenu des PDF</h3><p class="mt-0.5 text-xs text-slate-400">Textes imprimés sur les devis, proformas et factures</p></div><div class="grid gap-5 p-5 sm:grid-cols-2 sm:p-6"><label><span class="label">Entête personnalisée</span><textarea wire:model="form.document_header" rows="4" class="field" placeholder="Texte affiché avant le destinataire…"></textarea><small class="mt-1 block text-[10px] text-slate-400">Utilisez un texte court pour préserver la mise en page.</small></label><label><span class="label">Pied de page</span><textarea wire:model="form.document_footer" rows="4" class="field" placeholder="Coordonnées bancaires, remerciements…"></textarea></label><label><span class="label">Conditions de vente</span><textarea wire:model="form.document_terms" rows="5" class="field" placeholder="Délais, pénalités, validité…"></textarea></label><label><span class="label">Mentions légales</span><textarea wire:model="form.legal_notice" rows="5" class="field" placeholder="Forme juridique, capital, immatriculation…"></textarea></label></div></section>
                    @endif
                    <div class="flex justify-end"><button class="btn-primary" wire:loading.attr="disabled"><x-icon name="check" :size="16"/><span wire:loading.remove>Enregistrer les paramètres</span><span wire:loading>Enregistrement…</span></button></div>
                </form>
            @else
                <section class="panel overflow-hidden"><div class="flex items-center justify-between gap-3 border-b border-slate-100 px-5 py-4 sm:px-6"><div><h3 class="font-extrabold text-slate-950">Utilisateurs & rôles</h3><p class="mt-0.5 text-xs text-slate-400">{{ $users->where('is_active',true)->count() }} compte(s) actif(s)</p></div><button wire:click="createUser" class="btn-primary"><x-icon name="plus" :size="16"/><span class="hidden sm:inline">Nouvel utilisateur</span><span class="sm:hidden">Ajouter</span></button></div><div class="divide-y divide-slate-100">@foreach($users as $user)<div class="flex items-center gap-3 px-4 py-4 sm:px-6"><span class="grid size-10 shrink-0 place-items-center overflow-hidden rounded-xl bg-indigo-50 text-xs font-black text-indigo-600">@if($user->avatar_url)<img src="{{ $user->avatar_url }}" alt="Photo de {{ $user->name }}" class="h-full w-full object-cover">@else{{ strtoupper(substr($user->name,0,2)) }}@endif</span><div class="min-w-0 flex-1"><div class="flex items-center gap-2"><p class="truncate text-sm font-extrabold text-slate-900">{{ $user->name }}</p>@if($user->id === auth()->id())<span class="rounded-full bg-cyan-50 px-2 py-0.5 text-[9px] font-bold text-cyan-700">Vous</span>@endif</div><p class="truncate text-xs text-slate-400">{{ $user->email }}</p></div><div class="hidden text-right sm:block"><p class="text-xs font-bold text-slate-600">{{ $user->role === 'admin' ? 'Administrateur' : 'Gestionnaire' }}</p><p class="mt-0.5 text-[10px] {{ $user->is_active ? 'text-emerald-600' : 'text-rose-500' }}">{{ $user->is_active ? 'Compte actif' : 'Compte désactivé' }}</p></div><span class="size-2.5 shrink-0 rounded-full {{ $user->is_active ? 'bg-emerald-400' : 'bg-slate-300' }} sm:hidden"></span><button wire:click="editUser({{ $user->id }})" class="icon-button" title="Modifier"><x-icon name="edit" :size="16"/></button></div>@endforeach</div></section>
            @endif
        </div>
    </div>

    @if($showUserForm)
        <div class="mobile-sheet fixed inset-0 z-[90] flex items-center justify-center bg-slate-950/60 p-4 backdrop-blur-sm" x-data x-on:keydown.escape.window="$wire.set('showUserForm',false)"><form wire:submit="saveUser" class="max-h-[92dvh] w-full max-w-lg overflow-y-auto rounded-2xl bg-white shadow-2xl"><div class="sticky top-0 z-10 flex items-center justify-between border-b border-slate-100 bg-white/95 px-5 py-4 backdrop-blur"><div><h3 class="text-lg font-extrabold text-slate-950">{{ $editingUserId ? 'Modifier l’utilisateur' : 'Nouvel utilisateur' }}</h3><p class="mt-0.5 text-xs text-slate-400">Accès et niveau d’autorisation</p></div><button type="button" wire:click="$set('showUserForm',false)" class="topbar-button border-0 shadow-none"><x-icon name="x" :size="19"/></button></div><div class="grid gap-5 p-5 sm:grid-cols-2 sm:p-6">
                    <div class="sm:col-span-2">
                        <span class="label">Photo de profil</span>
                        <div class="flex items-center gap-4 rounded-2xl border border-slate-200 bg-slate-50 p-4">
                            <span class="grid size-20 shrink-0 place-items-center overflow-hidden rounded-2xl bg-indigo-100 text-lg font-black text-indigo-600 ring-4 ring-white">
                                @if($userAvatar)<img src="{{ $userAvatar->temporaryUrl() }}" alt="Aperçu" class="h-full w-full object-cover">@elseif($currentUserAvatar && !$removeUserAvatar)<img src="{{ asset('storage/'.$currentUserAvatar) }}" alt="Photo actuelle" class="h-full w-full object-cover">@else{{ strtoupper(substr($userForm['name'] ?: 'UT',0,2)) }}@endif
                            </span>
                            <div class="min-w-0 flex-1">
                                <label class="btn-secondary cursor-pointer"><x-icon name="plus" :size="15"/>Choisir une photo<input wire:model="userAvatar" type="file" accept="image/jpeg,image/png,image/webp" class="sr-only"></label>
                                <p class="mt-2 text-[10px] leading-4 text-slate-400">JPG, PNG ou WebP · 2 Mo maximum. L’image sera recadrée automatiquement.</p>
                                @if($currentUserAvatar)<label class="mt-2 flex items-center gap-2 text-xs font-semibold text-rose-600"><input wire:model.live="removeUserAvatar" type="checkbox">Supprimer la photo actuelle</label>@endif
                            </div>
                        </div>
                        @error('userAvatar')<small class="mt-1 block text-xs font-semibold text-rose-600">{{ $message }}</small>@enderror
                    </div>
                    <label><span class="label">Nom complet *</span><input wire:model="userForm.name" class="field">@error('userForm.name')<small class="mt-1 block text-xs text-rose-600">{{ $message }}</small>@enderror</label>
                    <label><span class="label">Adresse email *</span><input wire:model="userForm.email" type="email" class="field">@error('userForm.email')<small class="mt-1 block text-xs text-rose-600">{{ $message }}</small>@enderror</label>
                    <label><span class="label">Rôle</span><select wire:model="userForm.role" class="field"><option value="manager">Gestionnaire</option><option value="admin">Administrateur</option></select>@error('userForm.role')<small class="mt-1 block text-xs font-semibold text-rose-600">{{ $message }}</small>@enderror</label>
                    <label><span class="label">Mot de passe {{ $editingUserId ? '' : '*' }}</span><input wire:model="userForm.password" type="password" class="field" placeholder="{{ $editingUserId ? 'Laisser vide pour conserver' : '8 caractères minimum' }}">@error('userForm.password')<small class="mt-1 block text-xs text-rose-600">{{ $message }}</small>@enderror</label>
                    <label class="flex items-center gap-2.5 rounded-xl bg-slate-50 p-3 text-sm font-semibold"><input wire:model="userForm.is_active" type="checkbox">Compte actif</label>
                </div><div class="sticky bottom-0 flex justify-end gap-2 border-t border-slate-100 bg-slate-50/95 p-4 backdrop-blur"><button type="button" wire:click="$set('showUserForm',false)" class="btn-secondary">Annuler</button><button class="btn-primary">Enregistrer</button></div></form></div>
    @endif
</div>