<div class="space-y-6">
    <x-page-header eyebrow="Catalogue" title="Produits & services" description="Gardez vos tarifs, taxes, unités et niveaux de stock prêts pour la facturation.">
        <x-slot:actions><a href="{{ route('categories.index') }}" wire:navigate class="btn-secondary"><x-icon name="filter" :size="16"/><span class="hidden sm:inline">Gérer les catégories</span><span class="sm:hidden">Catégories</span></a><button wire:click="create" class="btn-primary"><x-icon name="plus" :size="16"/>Nouvel article</button></x-slot:actions>
    </x-page-header>

    <section class="grid grid-cols-3 gap-3">
        @foreach([['Articles actifs',$summary['active'],'box','bg-indigo-50 text-indigo-600'],['Catégories',$summary['categories'],'filter','bg-cyan-50 text-cyan-600'],['Stock faible',$summary['lowStock'],'alert',$summary['lowStock'] ? 'bg-rose-50 text-rose-600' : 'bg-emerald-50 text-emerald-600']] as [$label,$value,$icon,$color])
            <article class="stat-card"><div class="flex items-start justify-between gap-2"><p class="text-[9px] font-extrabold uppercase tracking-wider text-slate-400 sm:text-xs">{{ $label }}</p><span class="hidden size-8 place-items-center rounded-xl sm:grid {{ $color }}"><x-icon :name="$icon" :size="16"/></span></div><p class="mt-3 text-xl font-black text-slate-950">{{ $value }}</p></article>
        @endforeach
    </section>

    <section class="panel flex flex-col gap-3 p-3 sm:flex-row sm:p-4">
        <div class="relative min-w-0 flex-1"><x-icon name="search" :size="17" class="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input wire:model.live.debounce.300ms="search" placeholder="Nom ou référence de l’article…" class="field pl-10"></div>
        <div class="flex gap-2"><select wire:model.live="categoryFilter" class="field min-w-0 flex-1 sm:w-56"><option value="">Toutes les catégories</option>@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select>@if($hasFilters)<button wire:click="resetFilters" class="topbar-button shrink-0 text-rose-500"><x-icon name="x" :size="17"/></button>@endif</div>
    </section>

    <section class="panel overflow-hidden">
        <div class="hidden overflow-x-auto md:block table-scroll"><table class="w-full min-w-[760px] text-left text-sm"><thead><tr class="border-b border-slate-100 bg-slate-50/80 text-[10px] font-extrabold uppercase tracking-wider text-slate-400"><th class="px-5 py-3.5">Article</th><th class="px-5 py-3.5">Catégorie</th><th class="px-5 py-3.5 text-right">Prix HT</th><th class="px-5 py-3.5 text-center">TVA</th><th class="px-5 py-3.5">Stock</th><th class="w-24 px-5 py-3.5"></th></tr></thead><tbody class="divide-y divide-slate-100">
            @forelse($products as $product)
                <tr class="transition hover:bg-slate-50/60"><td class="px-5 py-4"><div class="flex items-center gap-3"><span class="grid size-9 shrink-0 place-items-center rounded-xl bg-indigo-50 text-indigo-600"><x-icon name="box" :size="17"/></span><div class="min-w-0"><p class="max-w-[280px] truncate font-extrabold text-slate-900">{{ $product->name }}</p><p class="mt-0.5 text-xs text-slate-400">{{ $product->sku ?: 'Sans référence' }} · {{ $product->unit }} @if(!$product->is_active)· <span class="text-rose-500">Inactif</span>@endif</p></div></div></td><td class="px-5 py-4"><span class="rounded-full bg-slate-100 px-2.5 py-1 text-[11px] font-bold text-slate-600">{{ $product->category?->name ?? 'Non classé' }}</span></td><td class="px-5 py-4 text-right font-extrabold text-slate-950">{{ number_format($product->unit_price,0,',',' ') }} <small class="text-slate-400">{{ $currency }}</small></td><td class="px-5 py-4 text-center text-xs font-semibold text-slate-600">{{ number_format($product->tax_rate,1,',',' ') }} %</td><td class="px-5 py-4">@if($product->track_stock)<span class="inline-flex items-center gap-1.5 text-xs font-bold {{ $product->stock_quantity <= 5 ? 'text-rose-600' : 'text-emerald-600' }}"><span class="size-1.5 rounded-full {{ $product->stock_quantity <= 5 ? 'bg-rose-500' : 'bg-emerald-500' }}"></span>{{ number_format($product->stock_quantity,3,',',' ') }}</span>@else<span class="text-xs text-slate-400">Non suivi</span>@endif</td><td class="px-5 py-4"><div class="flex justify-end gap-1"><button wire:click="edit({{ $product->id }})" class="icon-button" title="Modifier"><x-icon name="edit" :size="16"/></button><button wire:click="delete({{ $product->id }})" wire:confirm="Supprimer définitivement cet article ?" class="icon-button text-rose-500" title="Supprimer"><x-icon name="trash" :size="16"/></button></div></td></tr>
            @empty<tr><td colspan="6"><x-empty-state icon="box" :title="$hasFilters ? 'Aucun article trouvé' : 'Votre catalogue est vide'" description="Ajoutez des produits ou services pour remplir plus vite vos documents."><x-slot:action><button wire:click="create" class="btn-primary"><x-icon name="plus" :size="16"/>Ajouter un article</button></x-slot:action></x-empty-state></td></tr>@endforelse
        </tbody></table></div>

        <div class="grid gap-0 divide-y divide-slate-100 md:hidden">@forelse($products as $product)<article class="p-4"><div class="flex items-start gap-3"><span class="grid size-10 shrink-0 place-items-center rounded-xl bg-indigo-50 text-indigo-600"><x-icon name="box" :size="18"/></span><div class="min-w-0 flex-1"><div class="flex items-start justify-between gap-2"><div class="min-w-0"><h3 class="truncate text-sm font-extrabold text-slate-950">{{ $product->name }}</h3><p class="mt-0.5 text-[10px] text-slate-400">{{ $product->sku ?: 'Sans référence' }} · {{ $product->category?->name ?? 'Non classé' }}</p></div><p class="shrink-0 text-sm font-black text-slate-950">{{ number_format($product->unit_price,0,',',' ') }} <small>{{ $currency }}</small></p></div><div class="mt-3 flex items-center justify-between"><span class="text-xs text-slate-500">TVA {{ number_format($product->tax_rate,1,',',' ') }} % · / {{ $product->unit }}</span>@if($product->track_stock)<span class="text-xs font-bold {{ $product->stock_quantity <= 5 ? 'text-rose-600' : 'text-emerald-600' }}">Stock {{ number_format($product->stock_quantity,3,',',' ') }}</span>@endif</div></div></div><div class="mt-3 flex justify-end gap-1 border-t border-slate-100 pt-3"><button wire:click="edit({{ $product->id }})" class="btn-ghost"><x-icon name="edit" :size="14"/>Modifier</button><button wire:click="delete({{ $product->id }})" wire:confirm="Supprimer cet article ?" class="btn-ghost text-rose-600"><x-icon name="trash" :size="14"/>Supprimer</button></div></article>@empty<x-empty-state icon="box" title="Aucun article"/>@endforelse</div>
        @if($products->hasPages())<div class="border-t border-slate-100 p-4">{{ $products->links() }}</div>@endif
    </section>

    @if($showForm)
        <div class="mobile-sheet fixed inset-0 z-[90] flex items-center justify-center bg-slate-950/60 p-4 backdrop-blur-sm" x-data x-on:keydown.escape.window="$wire.set('showForm',false)">
            <form wire:submit="save" class="max-h-[92dvh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white shadow-2xl">
                <div class="sticky top-0 z-10 flex items-center justify-between border-b border-slate-100 bg-white/95 px-5 py-4 backdrop-blur"><div><h3 class="text-lg font-extrabold text-slate-950">{{ $editingId ? 'Modifier l’article' : 'Nouvel article' }}</h3><p class="mt-0.5 text-xs text-slate-400">Produit, prestation ou abonnement</p></div><button type="button" wire:click="$set('showForm',false)" class="topbar-button border-0 shadow-none"><x-icon name="x" :size="19"/></button></div>
                <div class="grid gap-5 p-5 sm:grid-cols-2 sm:p-6">
                    <label><span class="label">Nom de l’article *</span><input wire:model="form.name" class="field" autofocus>@error('form.name')<small class="mt-1 block text-xs text-rose-600">{{ $message }}</small>@enderror</label><label><span class="label">Référence / SKU</span><input wire:model="form.sku" class="field" placeholder="Ex. SRV-001">@error('form.sku')<small class="mt-1 block text-xs text-rose-600">{{ $message }}</small>@enderror</label>
                    <label class="sm:col-span-2"><span class="label">Description</span><textarea wire:model="form.description" rows="2" class="field" placeholder="Description proposée dans les documents…"></textarea></label>
                    <label class="sm:col-span-2"><span class="flex items-center justify-between gap-3"><span class="label">Catégorie</span><a href="{{ route('categories.index') }}" wire:navigate class="mb-1 text-[10px] font-bold text-indigo-600 hover:text-indigo-700">Gérer les catégories →</a></span><select wire:model="form.category_id" class="field"><option value="">Non classé</option>@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select></label>
                    <label><span class="label">Prix unitaire HT *</span><div class="relative"><input wire:model="form.unit_price" type="number" min="0" step="0.01" class="field pr-16"><span class="absolute right-3 top-1/2 -translate-y-1/2 text-xs font-bold text-slate-400">{{ $currency }}</span></div></label><label><span class="label">TVA</span><div class="relative"><input wire:model="form.tax_rate" type="number" min="0" max="100" step="0.01" class="field pr-8"><span class="absolute right-3 top-1/2 -translate-y-1/2 text-xs font-bold text-slate-400">%</span></div></label>
                    <label><span class="label">Unité</span><input wire:model="form.unit" class="field" placeholder="unité, heure, mois…"></label><label><span class="label">Quantité en stock</span><input wire:model="form.stock_quantity" type="number" min="0" step="0.001" class="field" :disabled="!$wire.form.track_stock"></label>
                    <label class="flex items-center gap-2.5 rounded-xl bg-slate-50 p-3 text-sm font-semibold text-slate-700"><input wire:model.live="form.track_stock" type="checkbox">Suivre le stock</label><label class="flex items-center gap-2.5 rounded-xl bg-slate-50 p-3 text-sm font-semibold text-slate-700"><input wire:model="form.is_active" type="checkbox">Article actif</label>
                </div>
                <div class="sticky bottom-0 flex justify-end gap-2 border-t border-slate-100 bg-slate-50/95 p-4 backdrop-blur sm:p-5"><button type="button" wire:click="$set('showForm',false)" class="btn-secondary">Annuler</button><button class="btn-primary" wire:loading.attr="disabled"><span wire:loading.remove>Enregistrer</span><span wire:loading>Enregistrement…</span></button></div>
            </form>
        </div>
    @endif
</div>