<div class="space-y-6">
    <x-page-header eyebrow="Trésorerie" title="Paiements" description="Enregistrez les règlements et suivez ce qui reste réellement à encaisser.">
        <x-slot:actions><button wire:click="openForm" class="btn-primary"><x-icon name="plus" :size="16"/>Nouveau paiement</button></x-slot:actions>
    </x-page-header>

    <section class="grid grid-cols-3 gap-3">
        @foreach([['Total encaissé',number_format($summary['total'],0,',',' ').' '.$currency,'wallet','bg-emerald-50 text-emerald-600'],['Ce mois',number_format($summary['month'],0,',',' ').' '.$currency,'calendar','bg-indigo-50 text-indigo-600'],['Reste à encaisser',number_format($summary['outstanding'],0,',',' ').' '.$currency,'alert','bg-amber-50 text-amber-600']] as [$label,$value,$icon,$color])
            <article class="stat-card"><div class="flex items-start justify-between gap-2"><p class="text-[9px] font-extrabold uppercase tracking-wider text-slate-400 sm:text-xs">{{ $label }}</p><span class="hidden size-8 place-items-center rounded-xl sm:grid {{ $color }}"><x-icon :name="$icon" :size="16"/></span></div><p class="mt-3 truncate text-sm font-black text-slate-950 sm:text-xl">{{ $value }}</p></article>
        @endforeach
    </section>

    <section class="panel flex flex-col gap-3 p-3 sm:flex-row sm:p-4">
        <div class="relative min-w-0 flex-1"><x-icon name="search" :size="17" class="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input wire:model.live.debounce.300ms="search" placeholder="Facture, client ou référence…" class="field pl-10"></div>
        <div class="flex gap-2"><select wire:model.live="methodFilter" class="field min-w-0 flex-1 sm:w-52"><option value="">Tous les modes</option><option value="bank_transfer">Virement</option><option value="cash">Espèces</option><option value="card">Carte</option><option value="check">Chèque</option><option value="mobile_money">Mobile Money</option><option value="other">Autre</option></select>@if($hasFilters)<button wire:click="resetFilters" class="topbar-button shrink-0 text-rose-500"><x-icon name="x" :size="17"/></button>@endif</div>
    </section>

    <section class="panel overflow-hidden">
        <div class="hidden overflow-x-auto md:block table-scroll"><table class="w-full min-w-[800px] text-left text-sm"><thead><tr class="border-b border-slate-100 bg-slate-50/80 text-[10px] font-extrabold uppercase tracking-wider text-slate-400"><th class="px-5 py-3.5">Date</th><th class="px-5 py-3.5">Facture & client</th><th class="px-5 py-3.5">Mode</th><th class="px-5 py-3.5">Référence</th><th class="px-5 py-3.5 text-right">Montant</th><th class="w-14 px-4 py-3.5"></th></tr></thead><tbody class="divide-y divide-slate-100">
            @forelse($payments as $payment)
                @php $methodLabel = ['cash'=>'Espèces','bank_transfer'=>'Virement','card'=>'Carte','check'=>'Chèque','mobile_money'=>'Mobile Money','other'=>'Autre'][$payment->method] ?? $payment->method; @endphp
                <tr class="transition hover:bg-slate-50/60"><td class="px-5 py-4"><p class="font-semibold text-slate-700">{{ $payment->paid_at->format('d/m/Y') }}</p><p class="mt-0.5 text-[10px] text-slate-400">{{ $payment->recorder?->name ?? 'Système' }}</p></td><td class="px-5 py-4"><a href="{{ route('documents.edit',['invoice',$payment->document]) }}" wire:navigate class="font-extrabold text-indigo-600 hover:text-indigo-700">{{ $payment->document->number }}</a><p class="mt-0.5 max-w-[240px] truncate text-xs text-slate-400">{{ $payment->document->client->company_name }}</p></td><td class="px-5 py-4"><span class="rounded-full bg-slate-100 px-2.5 py-1 text-[11px] font-bold text-slate-600">{{ $methodLabel }}</span></td><td class="px-5 py-4 text-xs text-slate-500">{{ $payment->reference ?: '—' }}</td><td class="px-5 py-4 text-right"><p class="font-black text-emerald-600">+ {{ number_format($payment->amount,0,',',' ') }} <small>{{ $payment->document->currency }}</small></p></td><td class="px-4 py-4"><button wire:click="delete({{ $payment->id }})" wire:confirm="Supprimer ce paiement et recalculer le solde ?" class="icon-button text-rose-500" title="Supprimer"><x-icon name="trash" :size="16"/></button></td></tr>
            @empty<tr><td colspan="6"><x-empty-state icon="wallet" :title="$hasFilters ? 'Aucun paiement trouvé' : 'Aucun paiement enregistré'" description="Les encaissements apparaîtront ici avec leur facture et leur référence."><x-slot:action><button wire:click="openForm" class="btn-primary"><x-icon name="plus" :size="16"/>Enregistrer un paiement</button></x-slot:action></x-empty-state></td></tr>@endforelse
        </tbody></table></div>
        <div class="divide-y divide-slate-100 md:hidden">@forelse($payments as $payment)@php $methodLabel = ['cash'=>'Espèces','bank_transfer'=>'Virement','card'=>'Carte','check'=>'Chèque','mobile_money'=>'Mobile Money','other'=>'Autre'][$payment->method] ?? $payment->method; @endphp<article class="p-4"><div class="flex items-start justify-between gap-3"><div class="min-w-0"><a href="{{ route('documents.edit',['invoice',$payment->document]) }}" wire:navigate class="text-sm font-extrabold text-indigo-600">{{ $payment->document->number }}</a><p class="mt-0.5 truncate text-xs text-slate-400">{{ $payment->document->client->company_name }}</p></div><p class="shrink-0 text-sm font-black text-emerald-600">+ {{ number_format($payment->amount,0,',',' ') }} <small>{{ $payment->document->currency }}</small></p></div><div class="mt-3 flex items-center justify-between"><span class="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-bold text-slate-600">{{ $methodLabel }}</span><span class="text-[10px] text-slate-400">{{ $payment->paid_at->format('d/m/Y') }} · {{ $payment->reference ?: 'Sans référence' }}</span></div><div class="mt-3 flex justify-end border-t border-slate-100 pt-2"><button wire:click="delete({{ $payment->id }})" wire:confirm="Supprimer ce paiement ?" class="btn-ghost text-rose-600"><x-icon name="trash" :size="14"/>Supprimer</button></div></article>@empty<x-empty-state icon="wallet" title="Aucun paiement"/>@endforelse</div>
        @if($payments->hasPages())<div class="border-t border-slate-100 p-4">{{ $payments->links() }}</div>@endif
    </section>

    @if($showForm)
        <div class="mobile-sheet fixed inset-0 z-[90] flex items-center justify-center bg-slate-950/60 p-4 backdrop-blur-sm" x-data x-on:keydown.escape.window="$wire.set('showForm',false)">
            <form wire:submit="save" class="max-h-[92dvh] w-full max-w-lg overflow-y-auto rounded-2xl bg-white shadow-2xl">
                <div class="sticky top-0 z-10 flex items-center justify-between border-b border-slate-100 bg-white/95 px-5 py-4 backdrop-blur"><div><h3 class="text-lg font-extrabold text-slate-950">Enregistrer un paiement</h3><p class="mt-0.5 text-xs text-slate-400">Le solde et le statut seront actualisés</p></div><button type="button" wire:click="$set('showForm',false)" class="topbar-button border-0 shadow-none"><x-icon name="x" :size="19"/></button></div>
                <div class="grid gap-5 p-5 sm:grid-cols-2 sm:p-6">
                    <label class="sm:col-span-2"><span class="label">Facture à régler *</span>@if($invoices->isEmpty())<div class="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-semibold text-emerald-700">Toutes les factures sont soldées.</div>@else<select wire:model="invoice_id" wire:change="selectInvoice" class="field"><option value="">Sélectionner une facture</option>@foreach($invoices as $invoice)<option value="{{ $invoice->id }}">{{ $invoice->number }} — {{ $invoice->client->company_name }} · solde {{ number_format($invoice->balance,0,',',' ') }} {{ $invoice->currency }}</option>@endforeach</select>@endif @error('invoice_id')<small class="mt-1 block text-xs font-semibold text-rose-600">{{ $message }}</small>@enderror</label>
                    <label><span class="label">Date du paiement *</span><input wire:model="paid_at" type="date" class="field"></label><label><span class="label">Montant *</span><div class="relative"><input wire:model="amount" type="number" min="0" step="0.01" class="field pr-16"><span class="absolute right-3 top-1/2 -translate-y-1/2 text-xs font-bold text-slate-400">{{ $currency }}</span></div>@error('amount')<small class="mt-1 block text-xs font-semibold text-rose-600">{{ $message }}</small>@enderror</label>
                    <label><span class="label">Mode de paiement</span><select wire:model="method" class="field"><option value="bank_transfer">Virement bancaire</option><option value="cash">Espèces</option><option value="card">Carte bancaire</option><option value="check">Chèque</option><option value="mobile_money">Mobile Money</option><option value="other">Autre</option></select></label><label><span class="label">Référence</span><input wire:model="reference" class="field" placeholder="Transaction, chèque…"></label><label class="sm:col-span-2"><span class="label">Note interne</span><textarea wire:model="notes" rows="2" class="field" placeholder="Précision facultative…"></textarea></label>
                </div>
                <div class="sticky bottom-0 flex justify-end gap-2 border-t border-slate-100 bg-slate-50/95 p-4 backdrop-blur sm:p-5"><button type="button" wire:click="$set('showForm',false)" class="btn-secondary">Annuler</button><button class="btn-primary" wire:loading.attr="disabled" @disabled($invoices->isEmpty())><span wire:loading.remove>Enregistrer le paiement</span><span wire:loading>Enregistrement…</span></button></div>
            </form>
        </div>
    @endif
</div>